backend:
  name: github
  repo: SettleAPI/settle-developer-docs
  branch: dev

# when using the default proxy server port
local_backend: true

media_folder: 'docs/.vuepress/public/media'
public_folder: '/media'
publish_mode: editorial_workflow
collections:
  - label: 'Home'
    name: 'home'
    files:
      - label: 'Homepage'
        name: 'homepage'
        file: 'docs/index.md'
        delete: false
        fields:
          - { label: 'Home', name: 'home', widget: 'hidden', default: true }
          - {
              label: 'Hero image',
              name: 'heroImage',
              widget: 'image',
              required: false,
            }
          - { label: 'Hero text', name: 'heroText', widget: 'string' }
          - {
              label: 'Tagline',
              name: 'tagline',
              widget: 'string',
              required: false,
            }
          - { label: 'Action text', name: 'actionText', widget: 'string' }
          - { label: 'Action link', name: 'actionLink', widget: 'string' }
          - label: Features
            name: features
            widget: list
            fields:
              - { label: 'Title', name: 'title', widget: 'string' }
              - { label: 'Details', name: 'details', widget: 'string' }
          - {
              label: 'Footer',
              name: 'footer',
              widget: 'string',
              required: false,
            }
          - { label: 'Body', name: body, widget: markdown, required: false }
  - name: guides
    label: Guides
    label_singular: 'Guide'
    folder: docs/api/guides
    create: true
    # adding a nested object will show the collection folder structure
    nested:
      depth: 100 # max depth to show in the collection tree
      summary: '{{title}}' # optional summary for a tree node, defaults to the inferred title field
    fields:
      - label: Title
        name: title
        widget: string
      - label: Body
        name: body
        widget: markdown
    # adding a meta object with a path property allows editing the path of entries
    # moving an existing entry will move the entire sub tree of the entry to the new location
    meta: { path: { widget: string, label: 'Path', index_file: 'index' } }
