backend:
  name: github
  repo: SettleForDevelopers/Settle-Developer-Docs-with-Netlify-CMS
  branch: stage

# when using the default proxy server port
local_backend: true

media_folder: 'docs/.vuepress/public/media'
public_folder: '/media'
publish_mode: editorial_workflow
collections:
  - label: 'Home'
    name: 'home'
    files:
      - label: 'Homepage'
        name: 'homepage'
        file: 'docs/index.md'
        delete: false
        fields:
          - { label: 'Home', name: 'home', widget: 'hidden', default: true }
          - {
              label: 'Hero image',
              name: 'heroImage',
              widget: 'image',
              required: false,
            }
          - { label: 'Hero text', name: 'heroText', widget: 'string' }
          - {
              label: 'Tagline',
              name: 'tagline',
              widget: 'string',
              required: false,
            }
          - { label: 'Action text', name: 'actionText', widget: 'string' }
          - { label: 'Action link', name: 'actionLink', widget: 'string' }
          - label: Features
            name: features
            widget: list
            fields:
              - { label: 'Title', name: 'title', widget: 'string' }
              - { label: 'Details', name: 'details', widget: 'string' }
          - {
              label: 'Footer',
              name: 'footer',
              widget: 'string',
              required: false,
            }
          - { label: 'Body', name: body, widget: markdown, required: false }
  - label: 'Introduction'
    name: 'introduction'
    folder: 'docs/introduction'
    create: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Meta description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - {
          label: 'Permalink',
          name: 'permalink',
          widget: 'hidden',
          default: '/:slug',
        }
  - label: 'Guides'
    name: 'guides'
    folder: 'docs/guides'
    create: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Meta description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - {
          label: 'Permalink',
          name: 'permalink',
          widget: 'hidden',
          default: '/:slug',
        }
  - label: 'API Reference'
    name: 'types'
    folder: 'docs/api'
    create: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Meta description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - {
          label: 'Permalink',
          name: 'permalink',
          widget: 'hidden',
          default: '/:slug',
        }
  - label: 'API Resources'
    name: 'resources'
    folder: 'docs/api/resources'
    create: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Meta description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - {
          label: 'Permalink',
          name: 'permalink',
          widget: 'hidden',
          default: '/:slug',
        }
  - label: 'Tutorials'
    name: 'tutorials'
    folder: 'docs/tutorials/implementation-and-integration'
    create: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Meta description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - {
          label: 'Permalink',
          name: 'permalink',
          widget: 'hidden',
          default: '/:slug',
        }
