backend:
  name: github
  repo: SettleAPI/settle-developer-docs
  branch: dev

# when using the default proxy server port
local_backend: true

media_folder: 'docs/.vuepress/public/media'
public_folder: '/media'
publish_mode: editorial_workflow
collections:
  - label: 'Home'
    name: 'home'
    files:
      - label: 'Homepage'
        name: 'homepage'
        file: 'docs/index.md'
        delete: false
        fields:
          - { label: 'Home', name: 'home', widget: 'hidden', default: true }
          - {
              label: 'Hero image',
              name: 'heroImage',
              widget: 'image',
              required: false,
            }
          - { label: 'Hero text', name: 'heroText', widget: 'string' }
          - {
              label: 'Tagline',
              name: 'tagline',
              widget: 'string',
              required: false,
            }
          - { label: 'Action text', name: 'actionText', widget: 'string' }
          - { label: 'Action link', name: 'actionLink', widget: 'string' }
          - label: Features
            name: features
            widget: list
            fields:
              - { label: 'Title', name: 'title', widget: 'string' }
              - { label: 'Details', name: 'details', widget: 'string' }
              - { label: 'URL', name: 'url', widget: 'string' }
          - {
              label: 'Footer',
              name: 'footer',
              widget: 'string',
              required: false,
            }
          - { label: 'Body', name: body, widget: markdown, required: false }
  ## Guides ##
  # Introduction
  - name: introduction
    label: Introductions
    label_singular: 'Introduction document'
    
    folder: docs/api/guides/introduction
    create: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Meta description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  # Tutorials
  - name: tutorials
    label: Tutorials
    label_singular: 'Tutorial'
    folder: docs/api/guides/tutorials
    create: true
    # adding a nested object will show the collection folder structure
    nested:
      depth: 3 # max depth to show in the collection tree
      summary: '{{title}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Meta description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
    meta: { path: { widget: string, label: 'Path', index_file: 'index' } }
  # Best Practices
  - name: best-practices
    label: Best Practices
    label_singular: 'Best Practice document'
    folder: docs/api/guides/best-practices
    create: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Meta description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  # Quickstarts
  - name: quickstarts
    label: Quickstarts
    label_singular: 'Quickstart document'
    folder: docs/api/guides/quickstarts
    create: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Meta description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  ## Support
  - name: support
    label: Support
    label_singular: 'Support document'
    folder: docs/api/support
    create: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Meta description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  ## Other
  - name: other
    label: Other
    label_singular: 'Genereic document'
    folder: docs/api
    create: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Meta description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }