name: Create production promotion pull request
on:
  push:
    branches:
      - stage
jobs:
  productionPromotion:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: prod
      - name: Reset production branch
        run: |
          git fetch origin stage:stage
          git reset --hard stage
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: prod-promotion