name: Create *Promote Dev to Stage* Pull Request
on:
  push:
    branches:
      - 'dev'  # Push events to branches matching refs/heads/promote/dev
jobs:
  productionPromotion:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: stage
      - name: Reset stage branch
        run: |
          git fetch origin promote/dev:promote/dev
          git reset --hard promote/dev
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: promTo/stage