name: Create *Promote Dev to Stage* Pull Request
on:
  push:
    branches:
      - dev
jobs:
  stagePromotion:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: stage
      - name: Reset stage branch
        run: |
          git fetch origin dev:dev
          git reset --hard dev
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: promTo/stage